baseURL = 'https://freestyle-libre.pp.ua/'
languageCode = 'uk'
title = 'Freestyle Libre 🇺🇦'
theme = 'PaperMod'
publishDir = 'docs'

[params]
defaultTheme = 'auto'

[params.homeInfoParams]
Title = 'Hi there wave'
Content = 'Can be Info, links, about...'

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30


