baseURL = 'https://freestyle-libre.pp.ua/'
languageCode = 'uk'
title = 'FL Site'
theme = 'PaperMod'
publishDir = 'docs'

[params]
defaultTheme = "auto"

[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowShareButtons = true

[Params]
ShowReadingTime = true

[params]
ShowBreadCrumbs = true

