baseURL = 'https://freestyle-libre.pp.ua/'
languageCode = 'uk'
title = 'Freestyle Libre 🇺🇦'
theme = 'PaperMod'
publishDir = 'docs'

[params]
defaultTheme = 'auto'

[params.homeInfoParams]
Title = 'Freestyle Libre 🇺🇦'
Content = 'Система моніторингу рівня глюкози крові Фрістайл Лібре (FreeStyle Libre) дозволяє максимально ефективно контролювати рівень глюкози без болю та ускладнень.'

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "diaexpert.ua"
name = "diaexpert.ua"
url = "https://diaexpert.ua/product-category/monitoring-uk/"
weight = 30

[[menu.main]]
identifier = "nightscout"
name = "Nightscout"
url = "https://nightscout.pp.ua/"
weight = 40


